using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Common.Build.Generator;

[Generator]
public class TasksGenerator : IIncrementalGenerator
{
    private const string Source = """
                                  // This file was autogenerated by Common.Build.Generator. DO NOT MODIFY!

                                  using Cake.Frosting;
                                  using JetBrains.Annotations;

                                  [UsedImplicitly]
                                  [TaskName("Substitute")]
                                  public class SubstituteTask : Common.Build.Tasks.SubstituteTask;

                                  [UsedImplicitly]
                                  [TaskName("Build")]
                                  [IsDependentOn(typeof(SubstituteTask))]
                                  public class BuildTask : Common.Build.Tasks.BuildTask;

                                  [UsedImplicitly]
                                  [TaskName("Archive")]
                                  [IsDependentOn(typeof(BuildTask))]
                                  public class ArchiveTask : Common.Build.Tasks.ArchiveTask;

                                  [UsedImplicitly]
                                  [TaskName("Package")]
                                  [IsDependentOn(typeof(BuildTask))]
                                  public class PackageTask : Common.Build.Tasks.PackageTask;
                                  """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("CommonTasks.g.cs", SourceText.From(Source, Encoding.UTF8)));
    }
}
