using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Common.Build.Generator.Generators;

[Generator]
public class TasksGenerator : IIncrementalGenerator
{
    private const string Source =
        """
        // This file was autogenerated by Common.Build.Generator. DO NOT MODIFY!

        using Cake.Frosting;
        using JetBrains.Annotations;

        [UsedImplicitly]
        [TaskName("Archive")]
        [IsDependentOn(typeof(BuildTask))]
        public class ArchiveTask : Common.Build.Tasks.ArchiveTask;

        [UsedImplicitly]
        [TaskName("Build")]
        [IsDependentOn(typeof(SubstituteTask))]
        public class BuildTask : Common.Build.Tasks.BuildTask;

        [UsedImplicitly]
        [TaskName("Package")]
        [IsDependentOn(typeof(BuildTask))]
        public class PackageTask : Common.Build.Tasks.PackageTask;

        [UsedImplicitly]
        [TaskName("Substitute")]
        public class SubstituteTask : Common.Build.Tasks.SubstituteTask;

        [UsedImplicitly]
        [TaskName("Test")]
        [IsDependentOn(typeof(BuildTask))]
        public class TestTask : Common.Build.Tasks.TestTask;
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("CommonTasks.g.cs", SourceText.From(Source, Encoding.UTF8)));
    }
}
