when:
  - event: push
    branch: main

matrix:
  PROJECT:
    - Common.Build
    - Common.Build.Generator

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - bash build.sh --target Build --general-project ${PROJECT}
