when:
  - event: manual
  - event: push
    branch: main

matrix:
  PROJECT:
    - Common.Build
    - Common.Build.Generator

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - bash build.sh --target Build --general-project ${PROJECT}

  - name: lint
    image: jetbrains/qodana-dotnet2025.2
    environment:
      QODANA_TOKEN:
        from_secret: qodana_token
