on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET SDK 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: |
          bash build.sh --target Archive --general-project Common.Build --general-version $GITHUB_REF_NAME
          bash build.sh --target Archive --general-project Common.Build.Generator --general-version $GITHUB_REF_NAME
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: out/*.zip
